runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0

builtins:
- remote_api: yes
- appstats: on

handlers:

- url: /_ah/queue/.*
  script: naziscore.worker.app
  login: admin

- url: /_ah/cron/.*
  script: naziscore.cron.app
  login: admin

- url: .*
  script: naziscore.main.app

libraries:
- name: ssl
  version: latest
- name: webapp2
  version: latest
- name: yaml
  version: latest
